package mybeans.first;

import xmlpac.Data;
import xmlpac.DataHandler;
import xmlpac.DataSheet;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DataSheetTable extends JPanel {
    private DataSheetTableModel tableModel;
    private JPanel rootPanel = new JPanel();
    private JPanel panelButtons = new JPanel();
    private JButton addButton = new JButton("Add (+)");
    private JButton delButton = new JButton("Del (-)");
    private JScrollPane scrollPane;
    private JTable table = new JTable();
    private DataSheet dataSheet;

    public DataSheetTable() {
        rootPanel.setLayout(new BorderLayout(0, 0));
        panelButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));

        //DataHandler.parsingBySAX(dataSheet, DataHandler.getDataXML());

        dataSheet = new DataSheet();
        dataSheet.setDateItem(new Data());

        tableModel = new DataSheetTableModel(dataSheet.getDate());
        tableModel.setDataSheet(dataSheet);
        table.setModel(tableModel);

        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                tableModel.setRowCount(tableModel.getRowCount() + 1);
                tableModel.getDataSheet().setDateItem(new Data());
                table.revalidate();
                tableModel.fireDataSheetChange();
            }
        });

        delButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (tableModel.getRowCount() > 1) {
                    tableModel.setRowCount(tableModel.getRowCount() - 1);
                    tableModel.getDataSheet().removeDataItem(tableModel.getDataSheet().size() - 1);
                    table.revalidate();
                    tableModel.fireDataSheetChange();
                } else {
                    tableModel.getDataSheet().getDateItem(0).setDate("");
                    tableModel.getDataSheet().getDateItem(0).setX(0);
                    tableModel.getDataSheet().getDateItem(0).setY(0);
                    table.revalidate();
                    table.repaint();
                    tableModel.fireDataSheetChange();
                }
            }
        });

        panelButtons.add(addButton);
        panelButtons.add(delButton);

        scrollPane = new JScrollPane(table);
        scrollPane.setHorizontalScrollBarPolicy(
                ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(
                ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);


        rootPanel.add(scrollPane, BorderLayout.CENTER);
        rootPanel.add(panelButtons, BorderLayout.SOUTH);
        rootPanel.setVisible(true);
        setVisible(true);
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public DataSheetTableModel getTableModel() {
        return tableModel;
    }

    public void setModel(DataSheetTableModel tableModel) {
        this.tableModel = tableModel;
        table.revalidate();
    }

    public void revalidate() {
        if (table != null) table.revalidate();
    }

    public static void main(String[] args) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        new DataSheetTable();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        panelButtons = new JPanel();
        panelButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rootPanel.add(panelButtons, BorderLayout.SOUTH);
        addButton = new JButton();
        addButton.setText("Add (+)");
        panelButtons.add(addButton);
        delButton = new JButton();
        delButton.setText("Del (-)");
        panelButtons.add(delButton);
        scrollPane = new JScrollPane();
        rootPanel.add(scrollPane, BorderLayout.CENTER);
        table = new JTable();
        scrollPane.setViewportView(table);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
